// tile manifest for AssetManager
export const SFX_MANIFEST = [
    // - Jetpack -
    {
        type:"sound",
        src:"./lib/Sounds/Button_State_Hover.wav",
        id:"btnHover",
        data:4
    },
    {
        type:"sound",
        src:"./lib/Sounds/Click_Button.wav",
        id:"btnClick",
        data:4
    },
    {
        type:"sound",
        src:"./lib/Sounds/Collect_Power_up.wav",
        id:"collectPowerUp",
        data:4
    },
    {
        type:"sound",
        src:"./lib/Sounds/Enter_Space.wav",
        id:"enterSpace",
        data:4
    },
    {
        type:"sound",
        src:"./lib/Sounds/Enter_Surface.wav",
        id:"enterSurface",
        data:4
    },
    {
        type:"sound",
        src:"./lib/Sounds/Fall.wav",
        id:"fall",
        data:4
    },
    {
        type:"sound",
        src:"./lib/Sounds/Hit_By_Spikes.wav",
        id:"touchSpikes",
        data:4
    },
    {
        type:"sound",
        src:"./lib/Sounds/Jetpack.wav",
        id:"useJetpack",
        data:4
    },
    {
        type:"sound",
        src:"./lib/Sounds/Jump.wav",
        id:"jump",
        data:4
    },
    {
        type:"sound",
        src:"./lib/Sounds/Trampoline.wav",
        id:"touchTrampoline",
        data:4
    },
    {
        type:"sound",
        src:"./lib/Sounds/Breakable_Platforms.wav",
        id:"break",
        data:4
    },
    {
        type:"sound",
        src:"./lib/Sounds/Bubble_Platform_Disappear.wav",
        id:"bubble",
        data:4
    }
];